library digibear_icons_flutter;

// Code generated by Téodor Todorov (Creator of Digibear).
// DO NOT EDIT.
// Copyright 2021 Digibear.
// All rights reserved.

import 'package:digibear_icons_flutter/src/db_icon_styles.dart';
import 'package:flutter/widgets.dart';

/// [IconData] class for a [DbIcon]
class DbIconData {
  final DbLineIconData line;
  final DbFillIconData fill;
  final DbDuotoneIconData duotone;

  const DbIconData({
    required this.line,
    required this.fill,
    required this.duotone,
  });

  IconData fromStyle(DbIconStyle style) {
    switch (style) {
      case DbIconStyle.line:
        return line;
      case DbIconStyle.fill:
        return fill;
      case DbIconStyle.duotone:
        return duotone;
    }
  }
}

/// Extension of the [IconData] class for a [DbIcon] with the line style
class DbLineIconData extends IconData {
  const DbLineIconData(int codePoint)
      : super(
          codePoint,
          fontFamily: 'DigibearIconLine',
          fontPackage: 'digibear_icons_flutter',
        );
}

/// Extension of the [IconData] class for a [DbIcon] with the fill style
class DbFillIconData extends IconData {
  const DbFillIconData(int codePoint)
      : super(
          codePoint,
          fontFamily: 'DigibearIconFill',
          fontPackage: 'digibear_icons_flutter',
        );
}

/// Extension of the [IconData] class for a [DbIcon] with the duotone style
class DbDuotoneIconData extends IconData {
  final List<IconData>? secondary;

  const DbDuotoneIconData(int codePoint, {this.secondary})
      : super(
          codePoint,
          fontFamily: 'DigibearIconDuotone',
          fontPackage: 'digibear_icons_flutter',
        );
}
